// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import "server-only"

import * as React from "react"

export const Index: Record<string, Record<string, any>> = {
  radix: {},
  base: {},
}
